[build]
command = "npm run build"
publish = "client/build"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
directory = "server"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
